[package]
name = "lido_forward"
version = "0.1.0"
edition = "2023_11"

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true


[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.13.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.24.0" }

